SELECT CITY,
       LEN(CITY) AS LEN_CITY
  FROM STATION
 ORDER BY LEN_CITY, CITY
 OFFSET 0 ROWS
 FETCH FIRST 1 ROWS ONLY;

SELECT CITY,
       LEN(CITY) AS LEN_CITY
  FROM STATION
 ORDER BY LEN_CITY DESC, CITY DESC
 OFFSET 0 ROWS
 FETCH FIRST 1 ROWS ONLY;
